title: ryanhenderson.dev
logo: /assets/images/htxryan-logo-square.png
#email: htxryan@gmail.com
tagline: Ryan Henderson's Blog
description: >-
  Hello, I'm Ryan Henderson.<br/>I do things with computers and occasionally leave a note.<br/>I work for Pariveda in Houston, Texas.
baseurl: ""
permalink: /:title/
url: "https://ryanhenderson.dev"
twitter_username: htxryan
github_username:  htxryan
twitter:
  username: htxryan
  card: summary
social:
  name: Ryan Henderson
  links:
    - https://twitter.com/htxryan
    - https://www.linkedin.com/in/htxryan
    - https://github.com/htxryan
author: htxryan

webmaster_verifications:
  google: DsFgK79hz_6WqUgWwfIc7nq1izXaeFJuPaWHzQdCtx4
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

feed:
  excerpt_only: false
  

# Build settings
build: 20200328
# theme: jekyll-theme-clean-blog
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-seo-tag
  - jekyll-target-blank


# Theme Options (so-simple)
# skin: "/assets/css/skins/dark.css"
skin: "/assets/css/skins/light.css"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
google_analytics: UA-162098969-1
footer_links:
  - title: Twitter
    url: https://twitter.com/htxryan
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/htxryan
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://linkedin.com/in/htxryan
    icon: fab fa-linkedin
  - title: RSS
    url: feed.xml
    icon: fas fa-rss-square