import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import { cssVariablesTheme } from "./src/lib/shiki-theme.mjs";

export default defineConfig({
  site: "https://ryanhenderson.dev",
  // E6: sitemap is generated by `@astrojs/sitemap`. Pagefind is invoked
  // explicitly in the `build` script (`astro build && pagefind --site dist`)
  // so a failed index step fails the deploy. We do NOT use the
  // `astro-pagefind` integration — `src/pages/search.astro` owns its own
  // lazy-loading boot script that dynamically imports `/pagefind/pagefind-ui.js`
  // on first interaction (per advisory P1 #10's zero-bytes-on-other-routes
  // contract).
  integrations: [mdx(), sitemap()],
  trailingSlash: "always",
  build: {
    format: "directory",
  },
  // E4 — single Shiki invocation, theme bound to the E2 `--shiki-*` CSS
  // variable surface (advisory P2 #15). Light/dark switch by swapping the
  // underlying CSS variables under [data-theme="dark"], not by re-running
  // Shiki with a second theme.
  markdown: {
    shikiConfig: {
      theme: cssVariablesTheme,
    },
  },
});
