#Requires -Version 7.4
<#
.SYNOPSIS
  Infinity Loop - PowerShell reference template
  Structural translation of the bash infinity-loop.sh generated by: ca loop

.DESCRIPTION
  Autonomously processes beads epics via Claude Code sessions.
  This is a STATIC REFERENCE TEMPLATE -- not generated by ca loop.
  Copy and adapt for your project.

  Usage:
    pwsh -NonInteractive -File infinity-loop.ps1
    $env:LOOP_DRY_RUN = "1"; pwsh -NonInteractive -File infinity-loop.ps1  # Preview

.NOTES
  Known Limitations (Windows):
  - No screen/tmux equivalent: runs in foreground only.
    Use Start-Process for background execution (no attach/detach).
  - [WINDOWS GAP] No process group kill (kill -- -$PID).
    Stop-Process kills the target only, not its child tree.
  - [WINDOWS GAP] No CWD-scoped orphan cleanup.
    Cannot inspect a running process's working directory from PowerShell.
  - [WINDOWS GAP] Symlinks require Developer Mode on Windows 10/11.
    Falls back to file copy for .latest pointer.
  - Memory watchdog uses Get-CimInstance (WMI) -- slightly slower than /proc/meminfo.
  - [WINDOWS GAP] No review trigger system. The bash version supports --review-every N
    with inter-process signaling. This template runs epics sequentially without
    review triggers. Use the polish loop (via WSL2) for post-hoc review.
  - Claude Code on Windows runs tool commands in Git Bash internally,
    so prompts containing bash commands work regardless.
#>

# --- Strict Mode (equivalent to set -euo pipefail) ---
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true

# ============================================================
# Config
# ============================================================
$MAX_RETRIES = 1
$MODEL = "claude-opus-4-7[1m]"
$EPIC_IDS = ""  # Space-separated epic IDs, or empty for auto-discover
# Note: unlike the --epics CLI flag (which uses commas), this variable is space-separated
# because the PS1 splits on whitespace at line 257. Convert: "a,b,c" -> "a b c".
$LOG_DIR = ".compound-agent/agent_logs"
$MIN_FREE_MEMORY_PCT = if ($env:MIN_FREE_MEMORY_PCT) { [int]$env:MIN_FREE_MEMORY_PCT } else { 20 }
$WATCHDOG_THRESHOLD = if ($env:WATCHDOG_THRESHOLD) { [int]$env:WATCHDOG_THRESHOLD } else { 15 }
$WATCHDOG_INTERVAL = if ($env:WATCHDOG_INTERVAL) { [int]$env:WATCHDOG_INTERVAL } else { 30 }
$SESSION_STALE_TIMEOUT = if ($env:SESSION_STALE_TIMEOUT) { [int]$env:SESSION_STALE_TIMEOUT } else { 1800 }
# Set CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=95 in your environment to enable aggressive
# context compaction in long-running sessions (prevents context window exhaustion).

# ============================================================
# Helpers
# ============================================================
function Get-Timestamp { Get-Date -Format 'yyyy-MM-dd_HH-mm-ss' }
function Get-IsoTimestamp { (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ') }
function Get-EpochSeconds { [System.DateTimeOffset]::UtcNow.ToUnixTimeSeconds() }

function Log {
    param([string]$Message)
    # Write to stderr (consistent with bash version's >&2)
    [Console]::Error.WriteLine("[$(Get-Timestamp)] $Message")
}

function Die {
    param([string]$Message)
    Log "FATAL: $Message"
    exit 1
}

# --- CLI Prerequisites ---
if (-not (Get-Command claude -ErrorAction SilentlyContinue)) { Die "claude CLI required" }
if (-not (Get-Command bd -ErrorAction SilentlyContinue)) { Die "bd (beads) CLI required" }

New-Item -ItemType Directory -Force -Path $LOG_DIR | Out-Null

# ============================================================
# Crash Handler (equivalent to trap _loop_cleanup EXIT)
# ============================================================
# Wraps the entire main body in try/finally below.
# The finally block handles crash logging.

# ============================================================
# Memory Safety
# ============================================================

# [WINDOWS GAP] cleanup_orphans -- Cannot inspect process CWD on Windows.
# The bash version uses lsof/readlink to scope kills to the current repo.
# On Windows, we skip CWD filtering and match against the full command line
# (like pgrep -f) using WMI, which is broader but the best available.
function Invoke-OrphanCleanup {
    $killed = 0
    $patterns = @('vitest', 'go\.test', 'pytest', 'cargo\.test', 'node.*\.test\.')
    try {
        $procs = Get-CimInstance Win32_Process -ErrorAction SilentlyContinue
        foreach ($proc in $procs) {
            if ([string]::IsNullOrEmpty($proc.CommandLine)) { continue }
            foreach ($pattern in $patterns) {
                if ($proc.CommandLine -match $pattern) {
                    # [WINDOWS GAP] No CWD check -- kills ALL matching processes, not just repo-scoped ones
                    Stop-Process -Id $proc.ProcessId -Force -ErrorAction SilentlyContinue
                    $killed++
                    break  # Don't double-count across patterns
                }
            }
        }
    } catch { }
    if ($killed -gt 0) {
        Log "Cleaned up $killed orphan test processes"
        Start-Sleep -Seconds 2
    }
}

# get_memory_pct equivalent -- uses WMI via Get-CimInstance
function Get-FreeMemoryPct {
    try {
        $os = Get-CimInstance -ClassName Win32_OperatingSystem
        if ($os.TotalVisibleMemorySize -eq 0) { return $null }
        return [math]::Round(($os.FreePhysicalMemory / $os.TotalVisibleMemorySize) * 100)
    } catch {
        return $null
    }
}

# check_memory equivalent
function Test-MemoryOk {
    $freePct = Get-FreeMemoryPct
    if ($null -eq $freePct) { return $true }  # Can't measure, assume OK
    if ($freePct -lt $MIN_FREE_MEMORY_PCT) {
        Log "WARN: System memory ${freePct}% free (minimum: ${MIN_FREE_MEMORY_PCT}%)"
        return $false
    }
    Log "Memory OK: ${freePct}% free"
    return $true
}

# Memory watchdog -- background job that monitors memory and kills target PID
# [WINDOWS GAP] Stop-Process does NOT kill the process tree. Only the target PID.
$script:WatchdogJob = $null

function Start-MemoryWatchdog {
    param([int]$TargetPid, [string]$MemLog)
    $script:WatchdogJob = Start-Job -ScriptBlock {
        param($pid, $log, $thresh, $interval)
        while ($null -ne (Get-Process -Id $pid -ErrorAction SilentlyContinue)) {
            try {
                $os = Get-CimInstance -ClassName Win32_OperatingSystem
                $pct = [math]::Round(($os.FreePhysicalMemory / $os.TotalVisibleMemorySize) * 100)
                "$(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss') memory_free=${pct}%" | Add-Content $log
                if ($pct -lt $thresh) {
                    "$(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss') WATCHDOG: memory ${pct}% < ${thresh}%, killing PID $pid" | Add-Content $log
                    # [WINDOWS GAP] Stop-Process does NOT kill the process tree
                    Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
                    break
                }
            } catch { }
            Start-Sleep -Seconds $interval
        }
    } -ArgumentList $TargetPid, $MemLog, $WATCHDOG_THRESHOLD, $WATCHDOG_INTERVAL
}

function Stop-MemoryWatchdog {
    if ($null -ne $script:WatchdogJob) {
        Stop-Job $script:WatchdogJob -ErrorAction SilentlyContinue
        Remove-Job $script:WatchdogJob -Force -ErrorAction SilentlyContinue
        $script:WatchdogJob = $null
    }
}

# Stale output watchdog -- kills session if trace file stops growing
$script:StaleWatchdogJob = $null

function Start-StaleWatchdog {
    param([int]$TargetPid, [string]$TraceFile, [string]$LogFile)
    $script:StaleWatchdogJob = Start-Job -ScriptBlock {
        param($pid, $trace, $log, $interval, $timeout)
        $lastSize = 0
        $staleSecs = 0
        while ($null -ne (Get-Process -Id $pid -ErrorAction SilentlyContinue)) {
            Start-Sleep -Seconds $interval
            $curSize = 0
            if (Test-Path $trace) { $curSize = (Get-Item $trace).Length }
            if (($curSize -eq $lastSize) -and ($lastSize -gt 0)) {
                $staleSecs += $interval
                if ($staleSecs -ge $timeout) {
                    "$(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss') STALE_WATCHDOG: no output for ${staleSecs}s, killing PID $pid" | Add-Content $log
                    # [WINDOWS GAP] Stop-Process does NOT kill the process tree
                    Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
                    break
                }
            } else {
                $staleSecs = 0
            }
            $lastSize = $curSize
        }
    } -ArgumentList $TargetPid, $TraceFile, $LogFile, $WATCHDOG_INTERVAL, $SESSION_STALE_TIMEOUT
}

function Stop-StaleWatchdog {
    if ($null -ne $script:StaleWatchdogJob) {
        Stop-Job $script:StaleWatchdogJob -ErrorAction SilentlyContinue
        Remove-Job $script:StaleWatchdogJob -Force -ErrorAction SilentlyContinue
        $script:StaleWatchdogJob = $null
    }
}

# ============================================================
# JSON Parsing (equivalent to parse_json with jq/python3 fallback)
# ============================================================
# PowerShell's ConvertFrom-Json replaces jq entirely.
function Invoke-ParseJson {
    param(
        [Parameter(ValueFromPipeline)][string]$JsonInput,
        [string]$Filter
    )
    $data = $JsonInput | ConvertFrom-Json
    if ($data -is [array]) { $data = $data[0] }
    $parts = $Filter.TrimStart('.') -split '\.'
    $v = $data
    foreach ($p in $parts) {
        if ([string]::IsNullOrEmpty($p)) { continue }
        $v = $v.$p
    }
    return $v
}

# ============================================================
# Epic Selector
# ============================================================
function Test-DepsClosed {
    param([string]$EpicId)
    try {
        $depsJson = bd show $EpicId --json 2>$null
        if ([string]::IsNullOrEmpty($depsJson)) { return $true }
        $data = $depsJson | ConvertFrom-Json
        if ($data -is [array]) { $data = $data[0] }
        $deps = if ($null -ne $data.depends_on) { $data.depends_on }
                elseif ($null -ne $data.dependencies) { $data.dependencies }
                else { @() }
        foreach ($d in $deps) {
            $status = if ($d -is [string]) { 'open' } else { $d.status }
            if ($status -ne 'closed') {
                $blockId = if ($d -is [string]) { $d } else { $d.id }
                Log "Skip ${EpicId}: blocked by dependency $blockId (not closed)"
                return $false
            }
        }
        return $true
    } catch {
        return $true
    }
}

function Get-NextEpic {
    if (-not [string]::IsNullOrEmpty($EPIC_IDS)) {
        foreach ($epicId in ($EPIC_IDS -split '\s+')) {
            if ($script:Processed -contains $epicId) { continue }
            try {
                $json = bd show $epicId --json 2>$null
                $status = $json | Invoke-ParseJson -Filter '.status'
                if ($status -eq 'open') {
                    if (Test-DepsClosed $epicId) { return $epicId }
                }
            } catch { continue }
        }
        return $null
    } else {
        try {
            $json = bd list --type=epic --ready --json --limit=10 2>$null
            $items = $json | ConvertFrom-Json
            foreach ($item in $items) {
                if ($script:Processed -contains $item.id) { continue }
                if (Test-DepsClosed $item.id) { return $item.id }
            }
        } catch { }
        return $null
    }
}

# ============================================================
# Prompt Builder
# ============================================================
function Build-Prompt {
    param([string]$EpicId)
    # Six backticks (``````): here-strings pass backticks literally. Six backticks form
    # a valid 6-backtick markdown code fence, avoiding conflict with triple-backtick content.
    return @"
You are running in an autonomous infinity loop. Your task is to fully implement a beads epic.

## Step 1: Load context
Run these commands to prime your session:

``````bash
npx ca load-session
bd show $EpicId
``````

Read the epic details carefully. Understand scope, acceptance criteria, and sub-tasks.

## Step 2: Execute the workflow
Run the full compound workflow for this epic, starting from the plan phase
(spec-dev is already done -- the epic exists):

/compound:cook-it from plan -- Epic: $EpicId

Work through all phases: plan, work, review, compound.

## Step 3: On completion
When all work is done and tests pass:
1. Close the epic: ``bd close $EpicId``
2. Commit and push all changes
3. Output this exact marker on its own line:

EPIC_COMPLETE

## Step 4: On failure
If you cannot complete the epic after reasonable effort:
1. Add a note: ``bd update $EpicId --notes "Loop failed: <reason>"``
2. Output this exact marker on its own line:

EPIC_FAILED

## Step 5: On human required
If you hit a blocker that REQUIRES human action (account creation, API keys,
external service setup, design decisions you cannot make, etc.):
1. Add a note: ``bd update $EpicId --notes "Human required: <reason>"``
2. Output this exact marker followed by a short reason on the SAME line:

HUMAN_REQUIRED: <reason>

Example: HUMAN_REQUIRED: Need AWS credentials configured in .env

## Memory Safety Rules
- For Go work, use ``go test ./...`` in the go/ directory.
- NEVER run embedding tests unless the epic modifies embedding code.
- Between test runs, wait for all child processes to exit before starting another.

## Rules
- Do NOT ask questions -- there is no human. Make reasonable decisions.
- Do NOT stop early -- complete the full workflow.
- If tests fail, fix them. Retry up to 3 times before declaring failure.
- Use HUMAN_REQUIRED only for true blockers that no amount of retrying can solve.
- Commit incrementally as you make progress.
"@
}

# ============================================================
# Text Extractor (equivalent to extract_text)
# ============================================================
# Extracts assistant text from Claude Code stream-json events.
# Reads a JSONL file and writes extracted text to an output file.
function Invoke-ExtractText {
    param([string]$TraceFile, [string]$OutputFile)
    if (-not (Test-Path $TraceFile)) { return }
    $results = [System.Collections.Generic.List[string]]::new()
    switch -File $TraceFile {
        default {
            $line = $_.Trim()
            if ([string]::IsNullOrEmpty($line)) { continue }
            try {
                $obj = $line | ConvertFrom-Json -ErrorAction SilentlyContinue
                if ($obj.type -eq 'assistant') {
                    foreach ($block in $obj.message.content) {
                        if ($block.type -eq 'text' -and -not [string]::IsNullOrEmpty($block.text)) {
                            $results.Add($block.text)
                        }
                    }
                }
            } catch { }
        }
    }
    $results | Set-Content $OutputFile -Encoding utf8
}

# ============================================================
# Marker Detection
# ============================================================
function Find-Marker {
    param([string]$LogFile, [string]$TraceFile)

    # Primary: check extracted text with anchored patterns
    if ((Test-Path $LogFile) -and ((Get-Item $LogFile).Length -gt 0)) {
        $content = Get-Content $LogFile -Raw
        if ($content -match '(?m)^EPIC_COMPLETE$') { return 'complete' }
        if ($content -match '(?m)^HUMAN_REQUIRED:\s*(.+)$') {
            return "human:$($Matches[1])"
        }
        if ($content -match '(?m)^EPIC_FAILED$') { return 'failed' }
    }

    # Fallback: check raw trace JSONL (unanchored)
    if ((Test-Path $TraceFile) -and ((Get-Item $TraceFile).Length -gt 0)) {
        $content = Get-Content $TraceFile -Raw
        if ($content -match 'EPIC_COMPLETE') { return 'complete' }
        if ($content -match 'HUMAN_REQUIRED:') { return 'human:detected in trace' }
        if ($content -match 'EPIC_FAILED') { return 'failed' }
    }

    return 'none'
}

# ============================================================
# Observability
# ============================================================
$STATUS_FILE = Join-Path $LOG_DIR '.loop-status.json'
$EXEC_LOG = Join-Path $LOG_DIR 'loop-execution.jsonl'

function Write-LoopStatus {
    param([string]$Status, [string]$EpicId = '', [int]$Attempt = 0)
    if ($Status -eq 'idle') {
        @{ status = 'idle'; timestamp = (Get-IsoTimestamp) } | ConvertTo-Json -Compress | Set-Content $STATUS_FILE -Encoding utf8
    } else {
        @{ epic_id = $EpicId; attempt = $Attempt; started_at = (Get-IsoTimestamp); status = $Status } |
            ConvertTo-Json -Compress | Set-Content $STATUS_FILE -Encoding utf8
    }
}

function Write-ResultLog {
    param([string]$EpicId, [string]$Result, [int]$Attempts, [long]$Duration)
    @{ epic_id = $EpicId; result = $Result; attempts = $Attempts; duration_s = $Duration; timestamp = (Get-IsoTimestamp) } |
        ConvertTo-Json -Compress | Add-Content $EXEC_LOG -Encoding utf8
}

# ============================================================
# Main Loop
# ============================================================
$COMPLETED = 0
$FAILED_COUNT = 0
$SKIPPED = 0
$script:Processed = @()
$LOOP_START = Get-EpochSeconds

Log "=========================================="
Log "Infinity loop starting"
Log "=========================================="
Log "Config: max_retries=$MAX_RETRIES model=$MODEL"
if (-not [string]::IsNullOrEmpty($EPIC_IDS)) { Log "Targeting epics: $EPIC_IDS" }
else { Log "Targeting: all ready epics" }

try {
    while ($true) {
        # Memory safety: clean up orphans and check memory
        Invoke-OrphanCleanup
        if (-not (Test-MemoryOk)) {
            Log "FATAL: Memory pressure too high, stopping loop to prevent system freeze"
            Log "  Hint: set MIN_FREE_MEMORY_PCT (current: ${MIN_FREE_MEMORY_PCT}%) or kill background processes"
            $FAILED_COUNT++
            break
        }

        $EPIC_ID = Get-NextEpic
        if ($null -eq $EPIC_ID) { break }

        Log "=========================================="
        Log "Processing epic: $EPIC_ID"
        Log "=========================================="
        $EPIC_START = Get-EpochSeconds

        $ATTEMPT = 0
        $RESULT = 'pending'

        Write-LoopStatus 'running' $EPIC_ID 1

        while ($ATTEMPT -le $MAX_RETRIES) {
            $ATTEMPT++
            $TS = Get-Timestamp
            $LOGFILE = Join-Path $LOG_DIR "loop_${EPIC_ID}-${TS}.log"
            $TRACEFILE = Join-Path $LOG_DIR "trace_${EPIC_ID}-${TS}.jsonl"

            Write-LoopStatus 'running' $EPIC_ID $ATTEMPT

            # [WINDOWS GAP] Symlink update for .latest
            # Requires Developer Mode. Falls back to writing the filename to a text file.
            $latestPath = Join-Path $LOG_DIR '.latest'
            try {
                if (Test-Path $latestPath) { Remove-Item $latestPath -Force }
                New-Item -ItemType SymbolicLink -Path $latestPath -Target (Split-Path $TRACEFILE -Leaf) -ErrorAction Stop | Out-Null
            } catch {
                # Fallback: hard link (no Developer Mode needed, same volume only)
                if (Test-Path $latestPath) { Remove-Item $latestPath -Force }
                try {
                    New-Item -ItemType HardLink -Path $latestPath -Target $TRACEFILE -ErrorAction Stop | Out-Null
                } catch {
                    # Last resort: plain text file with filename
                    Split-Path $TRACEFILE -Leaf | Set-Content $latestPath -Encoding utf8
                }
            }

            Log "Attempt $ATTEMPT/$($MAX_RETRIES + 1) for $EPIC_ID (log: $LOGFILE)"

            # Clean stale phase state (non-critical, may fail)
            try { ca phase-check clean 2>$null } catch { }

            if ($env:LOOP_DRY_RUN) {
                Log "[DRY RUN] Would run claude session for $EPIC_ID"
                $RESULT = 'complete'
                break
            }

            $PROMPT = Build-Prompt $EPIC_ID
            $MEM_LOG = Join-Path $LOG_DIR "memory_${EPIC_ID}-${TS}.log"
            $STDERR_FILE = "${LOGFILE}.stderr"

            # Run Claude session as a background process for watchdog monitoring.
            # Prompt is written to a temp file and piped via stdin (-p -) to avoid
            # command-line length limits (32KiB on Windows) and special char corruption.
            # Using -NoNewWindow (not -WindowStyle Hidden) so the child inherits
            # environment variables (ANTHROPIC_API_KEY, etc.).
            $promptFile = Join-Path $LOG_DIR "prompt_${EPIC_ID}-${TS}.txt"
            $PROMPT | Set-Content -Path $promptFile -NoNewline -Encoding utf8

            # Note: if 'claude' resolves to a .cmd wrapper (npm install), Start-Process
            # may not forward stdin correctly. Workaround: install Claude Code natively
            # or use WSL2 path instead.
            $proc = Start-Process -FilePath "claude" `
                -ArgumentList '--dangerously-skip-permissions','--permission-mode','auto','--model',$MODEL,'--output-format','stream-json','--verbose','-p','-' `
                -NoNewWindow -PassThru `
                -RedirectStandardInput $promptFile `
                -RedirectStandardOutput $TRACEFILE `
                -RedirectStandardError $STDERR_FILE

            Start-MemoryWatchdog $proc.Id $MEM_LOG
            Start-StaleWatchdog $proc.Id $TRACEFILE $MEM_LOG
            $proc.WaitForExit()
            Stop-StaleWatchdog
            Stop-MemoryWatchdog

            # Clean up prompt temp file
            Remove-Item $promptFile -Force -ErrorAction SilentlyContinue

            # Detect if watchdog killed the session
            if ((Test-Path $MEM_LOG) -and (Select-String -Path $MEM_LOG -Pattern 'STALE_WATCHDOG:' -Quiet)) {
                Log "WARN: Session killed by stale output watchdog (see $MEM_LOG)"
                Invoke-OrphanCleanup
            } elseif ((Test-Path $MEM_LOG) -and (Select-String -Path $MEM_LOG -Pattern 'WATCHDOG:' -Quiet)) {
                Log "WARN: Session killed by memory watchdog (see $MEM_LOG)"
                Invoke-OrphanCleanup
            }

            # Extract text from trace (post-hoc since we can't tee + pipe on Windows easily)
            Invoke-ExtractText $TRACEFILE $LOGFILE

            # Append stderr to macro log
            if ((Test-Path $STDERR_FILE) -and ((Get-Item $STDERR_FILE).Length -gt 0)) {
                Get-Content $STDERR_FILE | Add-Content $LOGFILE
                Remove-Item $STDERR_FILE -Force
            }

            # Health check: warn if macro log extraction failed
            if ((Test-Path $TRACEFILE) -and ((Get-Item $TRACEFILE).Length -gt 0) -and
                (-not (Test-Path $LOGFILE) -or (Get-Item $LOGFILE).Length -eq 0)) {
                Log "WARN: Macro log is empty but trace has content (extract_text may have failed)"
            }

            $MARKER = Find-Marker $LOGFILE $TRACEFILE

            switch -Wildcard ($MARKER) {
                'complete' {
                    Log "Epic $EPIC_ID completed successfully"
                    $RESULT = 'complete'
                }
                'human:*' {
                    $reason = $MARKER -replace '^human:', ''
                    Log "Epic $EPIC_ID needs human action: $reason"
                    try { bd update $EPIC_ID --notes "Human required: $reason" 2>$null } catch { }
                    $RESULT = 'skip'
                }
                'failed' {
                    Log "Epic $EPIC_ID reported failure (attempt $ATTEMPT)"
                }
                default {
                    Log "Epic $EPIC_ID session ended without marker (attempt $ATTEMPT)"
                }
            }

            # break exits switch only, not while -- check result explicitly
            if ($RESULT -ne 'pending') { break }

            if ($ATTEMPT -le $MAX_RETRIES) {
                Log "Retrying $EPIC_ID..."
                Invoke-OrphanCleanup
                Start-Sleep -Seconds 5
            }
        }

        $EPIC_DURATION = (Get-EpochSeconds) - $EPIC_START

        if ($RESULT -eq 'complete') {
            if (-not $env:LOOP_DRY_RUN) {
                # Verify working tree is clean after epic completion
                $dirty = $false
                try { git diff --quiet 2>$null } catch { $dirty = $true }
                try { git diff --cached --quiet 2>$null } catch { $dirty = $true }
                if ($dirty) {
                    Log "WARN: Working tree dirty after epic completion, auto-committing"
                    try { git add -A 2>$null } catch { }
                    try { git commit -m "chore: auto-commit uncommitted changes from $EPIC_ID" 2>$null } catch { }
                }
                $COMPLETED++
                Write-ResultLog $EPIC_ID 'complete' $ATTEMPT $EPIC_DURATION
                Log "Epic $EPIC_ID done. Completed so far: $COMPLETED"
            }
        } elseif ($RESULT -eq 'skip') {
            $SKIPPED++
            Write-ResultLog $EPIC_ID 'skipped' $ATTEMPT $EPIC_DURATION
            Log "Epic $EPIC_ID skipped (human required). Continuing."
        } elseif ($RESULT -eq 'pending') {
            $FAILED_COUNT++
            Write-ResultLog $EPIC_ID 'failed' $ATTEMPT $EPIC_DURATION
            Log "Epic $EPIC_ID failed after $($MAX_RETRIES + 1) attempts. Stopping loop."
            $script:Processed += $EPIC_ID
            break
        }

        $script:Processed += $EPIC_ID
    }
} catch {
    # Crash handler -- catches terminating errors (strict mode, native command failures)
    Log "CRASH: $_"
    @{ status = 'crashed'; error = "$_"; timestamp = (Get-IsoTimestamp) } |
        ConvertTo-Json -Compress | Set-Content $STATUS_FILE -ErrorAction SilentlyContinue
} finally {
    Stop-MemoryWatchdog
    Stop-StaleWatchdog
}

# ============================================================
# Post Loop
# ============================================================
$TOTAL_DURATION = (Get-EpochSeconds) - $LOOP_START

if (-not $env:LOOP_DRY_RUN) {
    @{ type = 'summary'; completed = $COMPLETED; failed = $FAILED_COUNT; skipped = $SKIPPED; total_duration_s = $TOTAL_DURATION } |
        ConvertTo-Json -Compress | Add-Content $EXEC_LOG -Encoding utf8
    Write-LoopStatus 'idle'

    # Push to remote if available
    try {
        $null = git remote get-url origin 2>$null
        Log "Pushing to remote..."
        git push 2>&1
    } catch {
        Log "WARN: git push failed: $_"
    }
}

Log "=========================================="
Log "Loop finished"
Log "  Completed: $COMPLETED"
Log "  Failed:    $FAILED_COUNT"
Log "  Skipped:   $SKIPPED"
$minutes = [math]::Floor($TOTAL_DURATION / 60)
Log "  Duration:  ${TOTAL_DURATION}s (${minutes}m)"
Log "  Processed: $($script:Processed -join ' ')"
Log "=========================================="

# Exit code
if ($COMPLETED -eq 0 -and $FAILED_COUNT -eq 0) {
    Log "WARN: Zero epics completed -- all may be blocked or skipped"
    exit 2
}
if ($FAILED_COUNT -eq 0) { exit 0 } else { exit 1 }
